Document: gnaural
Title: Debian gnaural Manual
Author: <insert document author here>
Abstract: This manual describes what gnaural is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gnaural/gnaural.sgml.gz

Format: postscript
Files: /usr/share/doc/gnaural/gnaural.ps.gz

Format: text
Files: /usr/share/doc/gnaural/gnaural.text.gz

Format: HTML
Index: /usr/share/doc/gnaural/html/index.html
Files: /usr/share/doc/gnaural/html/*.html

  
